dist: bionic

language: c

compiler:
    - gcc

addons:
    apt:
      packages: [ fakeroot, p7zip-full, autoconf, automake, bison, build-essential,
        flex, gawk, gettext, gperf, libtool, pkg-config, zlib1g-dev, libgmp3-dev,
        libmpc-dev, libmpfr-dev, texinfo, python-docutils, libncurses5-dev, curl,
        autopoint, libltdl-dev, cmake, m4, perl, build-essential, pkg-config,
        libgmp3-dev, libmpfr-dev, libmpc-dev, python-docutils, mc, tinc, help2man, -y ]

before_script:
    - mkdir -p /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x && mkdir -p /opt/images/
    - cp -f ./trunk/tools/travis/* /opt && ./trunk/tools/travis_ci_build_trig.sh
    - rm -rf toolchain-mipsel/ && mv -f * .[^.]* /opt/rt-n56u
    - wget $toolchain_url && tar -xf mipsel-linux-uclibc.tar.xz -C /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x
    - ls -Alh /opt/rt-n56u && cd /opt/rt-n56u/trunk/

script:
    - for m in $targets; do fakeroot ./build_firmware_nohup $m && cp -f images/*.trx /opt/images/$m.trx; ./clear_tree_simple >/dev/null 2>&1; done

after_script:
    - GIT_VERSION=`git rev-parse --short=7 HEAD 2>/dev/null` && [ -n "$GIT_VERSION" ] && image_name=images_mt7620_ad_$GIT_VERSION || image_name=images_mt7620_ad
    - cd /opt/images; du -k *; md5sum *.trx |tee md5sum.txt; 7z a -mx=9 ${image_name}.7z ./*
    - "curl -m 180 -H 'Max-Days: 3' --upload-file ./${image_name}.7z https://transfer.sh/${image_name}.7z ; echo"

env:
    global:
      - targets="K2"
      - toolchain_url="https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz"
      - secure: "GGHrKCkSvtNDttSd6jMV8cm6Cqv0LvpKz4s55N/Nl3WduMV0W/sixAquQ6a3/MNIvfosVsE9J+etT6lIeKap1X1awnLzpTU2shi7jJN7pBwh/aomsKPpuGFF4w56cQKJqi7It3l6T/Xd02r059mbQkfx3H0MyjXlwcIf1rPhtnksxAQ7tFYmLMuCClahgN42+JL6Brmy2gkL3kY7W0rtUd6SZ7H16gTW+Rm1eJMU1kBMku9wz3cgu9jLuBrgE6RgDDE5nMfVimJbEWo2pkVJH2sTWu3nvZ3S+3WNHNJvkpb08Sx7NCB9IYrWQgzNHRd0YkptksDJ1qZNepaO03uHPZfscLl9O8UinJpkp1DCwnQK9yQ3SbbZy2S1i492c+93z2reTSrXu+PIe1U12tVmXx5Vk7RbWuErHW9+Uq1fYbqK9GvPtZbpHusiphA+5WeaNyRCO+9axjn9pGVnsaBWjyH2pKV4N7o1pQIydmPgxqmQe45y/oZ0rMIsLyUEImvCkDg4tfig22NierCbhT+LFnu1fHE1RpS2kzrwXmy/w5UNVAP3zF+hS59YVuSnRgP0sKuRZyTeHHGrIgNAdAv5fSjsGgHtYaKnMXoypXMETZAJFdnDGOJM5AYNhVAgWd59YcF4AaF0xZwz0w8t9q4rq1p50KJxu6sZW5XvhlqrOr0="

git:
    depth: 3
